        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 09 23:36:50 2016
        MODULE INIT_RANDOM_SEED__genmod
          INTERFACE 
            SUBROUTINE INIT_RANDOM_SEED
            END SUBROUTINE INIT_RANDOM_SEED
          END INTERFACE 
        END MODULE INIT_RANDOM_SEED__genmod
